name: Deploy to DEV
on:
  workflow_dispatch:
  push:
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: ⚙️ Get workflow config from 'workflow.json'
        id: get_workflow_vars
        run: |
          # Load Workflow config file
          wfconfig=`cat ./workflow.json`
          
          # Strip whitespace ---------------
          wfconfig="${wfconfig//'%'/'%25'}"
          wfconfig="${wfconfig//$'\n'/'%0A'}"
          wfconfig="${wfconfig//$'\r'/'%0D'}"
          
          #output the wfconfig
          echo "::set-output name=workflowConfigJson::$wfconfig"

      - name: Echo The JSON
        run: echo "${{ fromJSON(steps.get_workflow_vars.outputs.workflowConfigJson).webServer }}"

      - name: Check Server ID Web1
        if: fromJSON(steps.get_workflow_vars.outputs.workflowConfigJson).webServer == 'WEB1'
        env: 
          WEB_SERVER: ${{ secrets.IP_WEB1 }}
        run: echo "Set web server to Web1"

      - name: Check Server ID Web1
        if: fromJSON(steps.get_workflow_vars.outputs.workflowConfigJson).webServer == 'WEB2'
        env: 
          WEB_SERVER: ${{ secrets.IP_WEB2 }}
        run: echo "Set web server to Web2"

      - name: Check Server ID Web1
        if: fromJSON(steps.get_workflow_vars.outputs.workflowConfigJson).webServer == 'WEB3'
        env: 
          WEB_SERVER: ${{ secrets.IP_WEB3 }}
        run: echo "Set web server to Web3"