name: Deploy to DEV
on:
  workflow_dispatch:
  push:
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: ⚙️ Get workflow config from 'workflow.json'
        id: get_workflow_vars
        run: |
          # Load Workflow config file
          wfconfig=`cat ./workflow.json`
          
          # Strip whitespace ---------------
          wfconfig="${wfconfig//'%'/'%25'}"
          wfconfig="${wfconfig//$'\n'/'%0A'}"
          wfconfig="${wfconfig//$'\r'/'%0D'}"
          
          #output the wfconfig
          echo "::set-output name=workflowConfigJson::$wfconfig"

      - name: Echo The server ID
        run: echo "${{ fromJSON(steps.get_workflow_vars.outputs.workflowConfigJson).webServer }}"

      - name: Check Server ID Web1
        env: 
          IP_DEV1: secrets.IP_DEV1
          IP_DEV2: secrets.IP_DEV2
          IP_DEV3: secrets.IP_DEV3
        run: |
          webServerId=${{ fromJSON(steps.get_workflow_vars.outputs.workflowConfigJson).webServer }}

          if [[ $webServer == WEB1 ]]; then
            echo "WEB_SERVER=$IP_DEV1" >> $GITHUB_ENV
          
          elif [[ $webServer == WEB2 ]]; then
            echo "WEB_SERVER=$IP_DEV2" >> $GITHUB_ENV
          
          elif [[ $webServer == WEB3 ]]; then
            echo "WEB_SERVER=$IP_DEV3" >> $GITHUB_ENV
          
          else
            echo "No Web Server matches"
          fi

      - name: Echo The Server IP
        run: echo "${{ env.WEB_SERVER }}"